# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint:spec
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: docs
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: docs:markdown



  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build:browser
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build:node

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
